### ISSUE TITLE
wowpng requires a very specific version of Python

### ISSUE THREAD

**Issue by dazzag24** [BlockSigner/wowpng#2]
Using Ubuntu 18.04 on WSL with pipenv and Python 3.6.9

Start server:

```
:~/code/wowpng$ python webserver.py --port=8080
[I 200211 11:02:13 webserver:135] Using '/tmp/tmpz2lxb9op' as working direcctory.
```

In another terminal, send the PDF to convert:

```
~/code/wowpng$ curl -F pdf=@sample.pdf http://localhost:8080/convert        
{"status": "ok", "id": "ktshn"}
```

Server logs:
```
[I 200211 11:02:22 web:2246] 200 POST /convert (127.0.0.1) 6.81ms
```

then use client to request result:
```
~/code/wowpng$ curl http://localhost:8080/convert/ktshn
<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>
```

Server logs:

```
[E 200211 11:07:21 web:1788] Uncaught exception GET /convert/ktshn (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/convert/ktshn', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/xxxx/.local/share/virtualenvs/wowpng-ihQDJ5Sv/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "webserver.py", line 98, in get
        output = result.result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/xxxx/.local/share/virtualenvs/wowpng-ihQDJ5Sv/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "webserver.py", line 98, in get
        output = result.result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/xxxx/.local/share/virtualenvs/wowpng-ihQDJ5Sv/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "webserver.py", line 98, in get
        output = result.result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "webserver.py", line 23, in pdf_to_png
        p = subprocess.run(["python", "pdf-to-png.py", fname], capture_output=True)
      File "/usr/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
    TypeError: __init__() got an unexpected keyword argument 'capture_output'
[E 200211 11:07:21 web:2246] 500 GET /convert/ktshn (127.0.0.1) 1.82ms
```
Any ideas?

thanks

**Comment by dazzag24** [comment]
Turns out that the Python docs are a bit misleading. From looking at https://docs.python.org/3/library/subprocess.html
I assumed that version 3 supports the capture_output parameter.  However it was only introduced in 3.7 and is not supported in 3.6.  However it can be emulated (see https://stackoverflow.com/questions/53209127/subprocess-unexpected-keyword-argument-capture-output).

With these modifications it no longer throws and error.  

This is a little annoying as I would have used 3.7 except that the Ubuntu deadsnakes ppa provides Python 3.7.6 which is too new and you run into this issue: https://github.com/davidjamesca/ctypesgen/issues/77

Let me know if you want a PR, but the changes are minimal.

Add to imports
```
from subprocess import PIPE
```

Change:

```
    p = subprocess.run(["python", "pdf-to-png.py", fname], capture_output=True)
```
to 
```
    p = subprocess.run(["python", "pdf-to-png.py", fname], stdout=PIPE, stderr=PIPE) 
```

Thanks

**Comment by betatim** [comment]
Thanks for trying this out and debugging! I think I would be fine with modifying the documentation to of wowpng to state that you need to use Python 3.7 instead of making it compatible with old versions of Python.

**Comment by dazzag24** [comment]
Hi,

That has the unfortunate side effect of making it impossible to use on a standard Ubuntu setup without making special efforts to install the exact version of Python that is required.  

Ubuntu comes with Python 3.6.9 as standard.  

And you can install 3.7.9 via a PPA, but its too new.

Thanks

**Comment by betatim** [comment]
That is a good point, in the end we do require a very specific version of Python (not too old, not too new). I had not considered that people would use their OS package manager to install Python and were using `conda` (or equivalent) to install the version required for each project. Or anyway deploying this as a docker container.

Do you want to make a PR with your suggested change?

**Comment by dazzag24** [comment]
Hi,

PR submitted.
Thanks
